{{/* Make sure all variables are set properly */}}
{{- include "tc.v1.common.loader.init" . -}}

{{- $secrets := include "wazuh.secrets" . | fromYaml -}}
{{- if $secrets -}}
  {{- $_ := mustMergeOverwrite .Values $secrets -}}
{{- end -}}

{{/* Render the templates */}}
{{- include "tc.v1.common.loader.apply" . -}}
